project:
  output-dir: _site/de

lang: de

website:
  navbar:
    left:
      - href: index.qmd
        text: Start
      - href: about.qmd
        text: Über mich
      - href: research.qmd
        text: Forschung
    right:
      - href: ../en/
        text: EN
      - href: ../de/
        text: DE
